#ifndef ENTIS_EVENT_H_
#define ENTIS_EVENT_H_

#include <stdbool.h>
#include <xcb/xcb.h>

enum entis_event_type {
  ENTIS_KEY_PRESS = XCB_KEY_PRESS,
  ENTIS_BUTTON_PRESS = XCB_BUTTON_PRESS,
  ENTIS_BUTTON_RELEASE = XCB_BUTTON_RELEASE,
  ENTIS_MOTION_NOTIFY = XCB_MOTION_NOTIFY,
  ENTIS_ENTER_NOTIFY = XCB_ENTER_NOTIFY,
  ENTIS_LEAVE_NOTIFY = XCB_LEAVE_NOTIFY,
  ENTIS_FOCUS_IN = XCB_FOCUS_IN,
  ENTIS_FOCUS_OUT = XCB_FOCUS_OUT,
  ENTIS_KEYMAP_NOTIFY = XCB_KEYMAP_NOTIFY,
  ENTIS_EXPOSE = XCB_EXPOSE,
  ENTIS_GRAPHICS_EXPOSURE = XCB_GRAPHICS_EXPOSURE,
  ENTIIS_NO_EXPOSURE = XCB_NO_EXPOSURE,
  ENTIS_VISIBILITY_NOTIFY = XCB_VISIBILITY_NOTIFY,
  ENTIS_CREATE_NOTIFY = XCB_CREATE_NOTIFY,
  ENTIS_DESTROY_NOTIFY =XCB_DESTROY_NOTIFY,
  ENTIS_UNMAP_NOTIFY = XCB_UNMAP_NOTIFY,
  ENTIS_MAP_NOTIFY = XCB_MAP_NOTIFY,
  ENTIS_MAP_REQUEST = XCB_MAP_REQUEST,
  ENTIS_REPARENT_NOTIFY = XCB_REPARENT_NOTIFY,
  ENTIS_CONFIGURE_NOTIFY = XCB_CONFIGURE_NOTIFY,
  ENTIS_CONFIGURE_REQUEST = XCB_CONFIGURE_REQUEST,
  ENTIS_GRAVITY_NOTIFY = XCB_GRAVITY_NOTIFY,
  ENTIS_RESIZE_REQUEST = XCB_RESIZE_REQUEST,
  ENTIS_CIRCULATE_NOTIFY = XCB_CIRCULATE_NOTIFY,
  ENTIS_CIRCULATE_REQUEST = XCB_CIRCULATE_REQUEST,
  ENTIS_PROPERTY_NOTIFY = XCB_PROPERTY_NOTIFY,
  ENTIS_SELECTION_CLEAR = XCB_SELECTION_CLEAR,
  ENTIS_SELECTION_REQUEST = XCB_SELECTION_REQUEST,
  ENTIS_SELECTION_NOTIFY = XCB_SELECTION_NOTIFY,
  ENTIS_CLIENT_MESSAGE = XCB_CLIENT_MESSAGE,
  ENTIS_MAPPING_NOTIFY = XCB_MAPPING_NOTIFY,
  ENTIS_GE_GENERIC = XCB_GE_GENERIC
};

void entis_poll_events();

#endif  // ENTIS_EVENT_H_
